### ISSUE TITLE
License

### ISSUE THREAD

**Issue by g7sim** [edenspiekermann/bright#1]
Can You please add a license like GPL, MIT or Apache. In some contries a missing license means that You claim the complete Copyright....

**Comment by maxhoffmann** [comment]
I’d love to help here, but I’m not an employee of Edenspiekermann anymore. 😕

**Comment by monachilada** [comment]
@maxhoffmann I made you a maintainer :)

**Comment by maxhoffmann** [comment]
Thanks @monachilada! I’ve added the MIT License. Hope this helps @g7sim!
